### ISSUE TITLE
[Bug] Error message is displayed if user input more than 255 characters in the password.

### ISSUE THREAD

**Issue by ryandupay** [kenkono/e-learning-laravel#25]
[Severity]
Major

[Priority]
Normal

[Steps]
1. Go to register user page.
2. Input username
3. Input very long password. Please set more than 255 characters

[Actual Result]
1. 

[Expected Result]

[Additional Information]

**Comment by kenkono** [comment]
@ryandupay 
Your opinion is that we should accept the long name over 255 characters, right?
I already modified edit user page not to accept over 255 characters.
So I think it is better to use the same rule.

**Comment by ryandupay** [comment]
> @ryandupay
> Your opinion is that we should accept the long name over 255 characters, right?
> I already modified edit user page not to accept over 255 characters.
> So I think it is better to use the same rule.
> https://gyazo.com/96f8d09954e1d10f3b8e62110aded1de

NO, should not accept more than 255.
- Please apply the rule to all password input 🙇
